cmake_minimum_required(VERSION 3.18)
project(TestPrivate)
find_package(Qt6 REQUIRED COMPONENTS Core Gui Widgets)
find_package(Qt6GuiPrivate REQUIRED)
message(STATUS "GuiPrivate_FOUND=${Qt6GuiPrivate_FOUND}")
if(TARGET Qt6::GuiPrivate)
  message(STATUS "Qt6::GuiPrivate EXISTS")
  add_executable(test_foo)
  target_link_libraries(test_foo Qt6::GuiPrivate)
else()
  message(FATAL_ERROR "Qt6::GuiPrivate MISSING")
endif()
