# gtk-settings.ini — Override settings.ini GTK3 untuk mixos
# File ini di-copy ke /etc/gtk-3.0/settings.ini di chroot.
# GTK3 dan GTK4 akan membaca setting ini sebagai fallback jika
# GSettings tidak tersedia.

[Settings]
gtk-theme-name = mixos-gtk
gtk-icon-theme-name = mixos-icons
gtk-cursor-theme-name = mixos-cursors
gtk-cursor-theme-size = 24
gtk-font-name = Inter 10.5
gtk-modules = appmenu-gtk-module
gtk-application-prefer-dark-theme = true
gtk-decoration-layout = close,minimize,maximize:menu
gtk-titlebar-right-click-menu = gtk-move-to-desktop
gtk-enable-animations = true
gtk-recent-files-max-age = 30
gtk-recent-files-enabled = true
gtk-xft-antialias = 1
gtk-xft-hinting = 1
gtk-xft-hintstyle = hintslight
gtk-xft-rgba = rgb
gtk-xft-dpi = 98304
